apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

images:
  - name: docker.io/kedacore/keda-metrics-apiserver:2.1.0
    newName: mohsinonxrm/keda-metrics-apiserver
    newTag: main
  - name: docker.io/kedacore/keda:2.1.0
    newName: mohsinonxrm/keda
    newTag: main
