#https://keda.sh/docs/2.1/concepts/scaling-jobs/
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: ydl-converter
spec:
  jobTargetRef:
    completions: 1
    parallelism: 1
    backoffLimit: 0
    template:
      spec:
        containers:
          - image: registry.neko.lab:5005/root/serverless/ydl-converter
            resources:
              requests:
                cpu: 400m
                memory: 50Mi
            name: ydl-converter
            imagePullPolicy: Always
            volumeMounts:
              - mountPath: /convert
                name: savedir
            env:
              - name: TZ
                value: Asia/Tokyo
              - name: REST_URL
                value: "http://ydl-apiserver.default.svc.cluster.local/"
              - name: LOG_FREQ
                value: "1s"
        restartPolicy: Never
        volumes:
          - name: savedir
            glusterfs:
              endpoints: glusterfs-cluster
              path: /gvol/Data/Temporary
              readOnly: false
  maxReplicaCount: 5
  successfulJobsHistoryLimit: 5
  triggers:
    - type: metrics-api
      metadata:
        targetValue: "1"
        url: "http://ydl-apiserver.default.svc.cluster.local/get?type=cnv"
        valueLocation: "tasks"
