apiVersion: v1
kind: Service
metadata:
  name: ydl-apiserver
spec:
  selector:
    app: ydl-apiserver
  ports:
    - protocol: TCP
      targetPort: 6001
      port: 80
      name: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ydl-apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ydl-apiserver
  template:
    metadata:
      labels:
        app: ydl-apiserver
    spec:
      containers:
        - name: ydl-apiserver
          image: ydl-apiserver:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 6001
