#https://keda.sh/docs/2.5/concepts/scaling-jobs/
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: ydl-converter
spec:
  triggers:
    - type: metrics-api
      metadata:
        targetValue: "1"
        url: "http://ydl-apiserver.default.svc.cluster.local/get?type=cnv"
        valueLocation: "tasks"
  jobTargetRef:
    completions: 1
    parallelism: 1
    backoffLimit: 0
    template:
      spec:
        containers:
          - image: ydl-converter:latest
            name: ydl-converter
            imagePullPolicy: Always
            volumeMounts:
              - mountPath: /convert
                name: savedir
            env:
              - name: REST_URL
                value: "http://ydl-apiserver.default.svc.cluster.local/"
        restartPolicy: Never
        volumes:
          - name: savedir
            emptyDir: {}
